### ISSUE TITLE
docs: document how to publish binary in GitHub release from release-plz.yml file

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1433]
## Motivations

If you don't use another file, you can use the default github token

## Solution
some thing like this:

```yml
name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        id: release-plz
        uses: MarcoIeni/release-plz-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  upload-assets:
    needs:
      - release-plz
    name: ${{ matrix.target }}
    if: needs.release-plz.outputs.releases_created == true && github.repository_owner == 'MarcoIeni' && startsWith(github.event.release.name, 'marco-test-one-v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # When updating this list, the reminder to update the target list in ci.yml.
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04
          - target: aarch64-apple-darwin
            os: macos-11
          - target: aarch64-pc-windows-msvc
            os: windows-2019
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
          - target: x86_64-apple-darwin
            os: macos-11
          - target: x86_64-pc-windows-msvc
            os: windows-2019
          - target: x86_64-unknown-freebsd
            os: ubuntu-22.04
          - target: universal-apple-darwin
            os: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - ... # here build and publish the binary to github release created by release-plz
```

Read the github action [output](https://release-plz.ieni.dev/docs/github/output) to determine what binaries you should build and publish.
Maybe we should add a "type" to the github action output? (`binary` or `library`).
