### ISSUE TITLE
Add flags to Github Actions command

### ISSUE THREAD

**Issue by mattstam** [MarcoIeni/release-plz#1593]
In the release-plz action:
```
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
```
It's not clear how to extend this with additional flags, such as `--no-verify`. If it's possible, it would be good to add to the docs. If it's not possible, it would be good to add it.
