### ISSUE TITLE
docs: release output linked to release-pr step

### ISSUE THREAD

**Issue by ddanielsantos** [MarcoIeni/release-plz#1816]
according to https://release-plz.ieni.dev/docs/github/output

the output of the `release-pr` command is:
```jsonc
{
prs: //,
pr: //,
prs_created: //
}
```

and for `release` command:
```jsonc
{
releases: //,
releases_created: //
}
```

however, a latter example in the same page demonstrates these two steps:
```yaml
  - name: Run release-plz
    id: release-plz # <--- ID used to refer to the outputs. Don't forget it.
    uses: MarcoIeni/release-plz-action@v0.5
    with:
      command: release-pr
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  - name: Tag released PRs
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASES: ${{ steps.release-plz.outputs.releases }}
```

since the first step uses `release-pr`, can I still save `.outputs.releases` in a env variable for the second step?
