### ISSUE TITLE
release-plz init doesn't allow license-file

### ISSUE THREAD

**Issue by erys** [MarcoIeni/release-plz#2286]
## Bug description

If using a non-standard license via the `license-file` field in `Cargo.toml`, `release-plz init` will fail because the `license` field is not set.

- Would you like to work on a fix? [y/n] y

## To Reproduce

Create a new project, setting mandatory fields in `Cargo.toml`, but using `license-file` instead of `license`, like 
```toml
# Cargo.toml
[package]
name = "release-plz-test"
version = "0.1.0"
edition = "2024"
description = 'test'
license-file = "LICENSE.md"

[dependencies]
```
The run `release-plz init`. You'll get an error like
```
2025-06-30T22:07:58.595866Z ERROR The following mandatory fields for crates.io are missing in Cargo.toml:
- `license` for package `release-plz-test`
See https://doc.rust-lang.org/cargo/reference/manifest.html
```

## Expected behavior

`release-plz init` allows `license-file` rather than `license`

## Environment

- OS: Windows 11
- release-plz version: [e.g. 0.1.0]
