### ISSUE TITLE
release-plz fails caused by wrong usage of sparse-registry feature

### ISSUE THREAD

**Issue by sassman** [MarcoIeni/release-plz#596]
## Bug description

```plain

  2023-03-10T08:42:29.889250Z ERROR  error while downloading packages

Caused by:
    usage of sparse registries requires `-Z sparse-registry`

Error: error while downloading packages

Caused by:
    usage of sparse registries requires `-Z sparse-registry`
Error: Process completed with exit code 1.

```
[see this action run](https://github.com/curlz-rs/curlz/actions/runs/4382533684/jobs/7672222882)

## To Reproduce

1. have a GitHub Action file like this:
```yaml
name: Release PR+Tag+Publish
on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release it all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
```
3. let it run for the release pr
4. observe the error in the actions log

## Expected behavior

As the message says, `cargo +nightly ...` should be used when using the new sparse index feature

## Environment

- GitHub Actions
- OS: Ubuntu 22.04 aka ubuntu-latest
- release-plz version: v0.2.53
