### ISSUE TITLE
update workspace version when specified

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#635]
When the package version is specified as
```toml
[package]
version.workspace = true
```

then we need to update the version defined in the root Cargo.toml:
```toml
[workspace.package]
# shared version of all public crates in the workspace
version = "0.10.2"
```

instead of the Cargo.toml of the single crate.

Requested [here](https://github.com/near/borsh-rs/pull/133#issuecomment-1480271704)
