### ISSUE TITLE
Configuration: add ability to change the git release name.

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#677]
## Motivations

The release now is called `{crate_name}v{tag}` if workspace or `v{tag}` if single crate.
Add ability to customize the name.

## Solution

In the `git_release` section of the configuration add something like this:

```toml
[package.my_pkg.git_release]
# Set an alternate name format for the git release
# Default: v${tag}.
name = "${tag}" # do not include `v`
```

Let's use `tera` for this since we already expose it to the user via git-cliff.

**Comment by LukeMathWalker** [comment]
I'm currently using the following configuration for `cargo-release`:

```toml
# Config for 'cargo release'
[workspace.metadata.release]
shared-version = true
consolidate-commits = true
tag-name = "{{version}}"
```

It lets me release all packages in my workspace with a single version and it generates a single tag (e.g. `0.1.9`).d
I was trying to migrate my release flow to `release-plz` but I can't seem to find an equivalent setting?

(Commenting here since it looks like the most appropriate issue)
