### ISSUE TITLE
Configuration options are not override correctly

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#688]
## Bug description

Specifying the configuration of a package, overrides the entire configuration of the package, not just the specified options.

For example, in this case:

```toml
[workspace.release]
allow_dirty = true

[package.marco-test-one.release]
no_verify = true
```

marco-test-one has allow_dirty = false.

## Solution

read config fields as Option

- [x] semver_check can be a bool
- [x] add `name` field in Package section
