### ISSUE TITLE
Trigger further git-tag-push workflows when using a custom personal GITHUB_TOKEN does not work

### ISSUE THREAD

**Issue by frol** [MarcoIeni/release-plz#706]
## Bug description

_Moving the discussion from https://github.com/near/near-cli-rs/pull/180#pullrequestreview-1388207568:_

I use a custom GITHUB_TOKEN (Classic token from my personal account as it was described in ["Triggering further workflow runs"](https://marcoieni.github.io/release-plz/github/trigger.html); see permissions below), and this solved the issue of triggering CI jobs for the PRs created by Release-plz, but it seems that it does not solve the issue for the created tags (there is a release.yml pipeline, which should be triggered when a new tag appears, and the last time I cut the release, I had to remove and manually push the tag in order to trigger the job).

<img width="778" alt="image" src="https://user-images.githubusercontent.com/304265/232758163-ac9f1f22-655c-418e-8f08-c8a4d7b71515.png">

Can Release-plz push the tag using GITHUB_TOKEN?

- Would you like to work on a fix? [y/n]: No, I don't have time at the moment

## To Reproduce

1. Setup GitHub Actions job that is triggered on new tags push
2. Use Release-plz with custom GITHUB_TOKEN
3. On a new version release a new tag will be pushed, but the CI job (1) does not get triggered

## Expected behavior

The "push-tag" pipelines should be triggered when Release-plz pushes a release tag.

## Environment

https://github.com/near/near-cli-rs/blob/master/.github/workflows/

- release-plz version: 0.4

**Comment by MarcoIeni** [comment]
When replacing
```yaml
on:
  tags:
    - "v*.*.*"  
```
with
```yaml
on:
  release:
    types: [published]
```

the other workflow is triggered. I wonder why 🤔

**Comment by MarcoIeni** [comment]
I got the issue!
You need to add the token in the `actions/checkout` step, too:

```yaml
- name: Checkout repository
  uses: actions/checkout@v3
  with:
    fetch-depth: 0
    token: ${{ secrets.MY_TOKEN }}
```

[Here](https://github.com/near/near-cli-rs/pull/185) is the PR.
